# Generated by Django 3.0.6 on 2020-06-08 17:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='name')),
                ('specie', models.CharField(max_length=20, verbose_name='specie')),
                ('birth_date', models.DateField(null=True, verbose_name='birth date')),
                ('register_date', models.DateField(auto_now_add=True, verbose_name='register date')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='owner')),
            ],
            options={
                'verbose_name_plural': 'Animals',
            },
        ),
        migrations.CreateModel(
            name='Disease',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='name')),
                ('recommendations', models.TextField(verbose_name='recommendations')),
                ('register_date', models.DateField(null=True, verbose_name='register date')),
                ('status', models.BooleanField(null=True)),
                ('cure_data', models.DateField(blank=True, null=True, verbose_name='cure date')),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Animal', verbose_name='animal')),
            ],
            options={
                'verbose_name_plural': 'Diseases',
            },
        ),
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='name')),
                ('dose', models.CharField(max_length=60, verbose_name='dose')),
                ('introduction_date', models.DateField(null=True, verbose_name='introduction date')),
                ('status', models.BooleanField(null=True)),
                ('end_data', models.DateField(blank=True, null=True, verbose_name='end date')),
                ('disease', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Disease')),
            ],
            options={
                'verbose_name_plural': 'Medicines',
            },
        ),
    ]
