# Generated by Django 3.0.6 on 2020-06-11 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="disease",
            name="cure_data",
            field=models.DateField(null=True, verbose_name="cure date"),
        ),
    ]
