# Generated by Django 3.0.5 on 2020-09-17 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20200611_2025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicine',
            name='end_data',
            field=models.DateField(null=True, verbose_name='end date'),
        ),
    ]
