# Generated by Django 3.0.5 on 2020-09-17 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20200917_1622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicine',
            name='end_data',
            field=models.DateField(blank=True, null=True, verbose_name='end date'),
        ),
    ]
