# Generated by Django 3.0.5 on 2020-09-21 11:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0017_auto_20200921_1254'),
        ('app', '0007_delete_appointment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField(null=True)),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Animal', verbose_name='animal')),
                ('doctor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.Doctor')),
                ('service', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.Service', verbose_name='service')),
                ('slot', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.Slot')),
            ],
            options={
                'verbose_name_plural': 'Appointments',
            },
        ),
    ]
