# Generated by Django 3.0.5 on 2020-09-24 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_appointment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Appointment',
        ),
    ]
