# Generated by Django 3.0.5 on 2020-09-27 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_appointment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='slot',
        ),
    ]
