# Generated by Django 3.0.5 on 2020-09-28 14:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0011_remove_appointment_slot"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appointment",
            name="animal",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="app.Animal",
                verbose_name="animal",
            ),
        ),
    ]
