# Generated by Django 3.0.5 on 2020-10-17 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0020_appointment_slot"),
    ]

    operations = [
        migrations.AddField(
            model_name="appointment",
            name="admin_only",
            field=models.BooleanField(null=True, verbose_name="staff only"),
        ),
    ]
