# Generated by Django 3.0.5 on 2020-10-17 05:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_appointment_admin_only'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='admin_only',
        ),
    ]
