# Generated by Django 3.0.5 on 2020-10-19 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0023_auto_20201019_1242"),
    ]

    operations = [
        migrations.AddField(
            model_name="disease",
            name="doctor",
            field=models.CharField(
                blank=True, max_length=40, null=True, verbose_name="name"
            ),
        ),
        migrations.AddField(
            model_name="medicine",
            name="doctor",
            field=models.CharField(
                blank=True, max_length=40, null=True, verbose_name="name"
            ),
        ),
    ]
