# Generated by Django 3.0.5 on 2020-08-28 11:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0002_doctor"),
    ]

    operations = [
        migrations.AlterField(
            model_name="doctor",
            name="profile",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="user.Profile"
            ),
        ),
    ]
