# Generated by Django 3.0.5 on 2020-08-28 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0005_auto_20200828_1406"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="image",
            field=models.ImageField(
                blank=True, upload_to="static/profile_images"
            ),
        ),
    ]
