# Generated by Django 3.0.5 on 2020-09-17 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_auto_20200917_1323'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctor',
            old_name='user',
            new_name='profile',
        ),
    ]
