# Generated by Django 3.0.5 on 2020-09-18 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0009_auto_20200917_1326"),
    ]

    operations = [
        migrations.AddField(
            model_name="doctor",
            name="patients",
            field=models.ManyToManyField(
                related_name="_doctor_patients_+", to="user.Profile"
            ),
        ),
    ]
