# Generated by Django 3.0.5 on 2020-09-20 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0015_auto_20200920_1552'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='slot',
            options={'verbose_name_plural': 'Slots'},
        ),
    ]
