# Generated by Django 3.0.5 on 2020-09-24 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0017_auto_20200921_1254'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='clients',
        ),
    ]
