# Generated by Django 3.0.5 on 2020-09-24 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0019_appointment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Appointment',
        ),
    ]
