# Generated by Django 3.0.5 on 2020-09-27 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_remove_appointment_slot'),
        ('user', '0020_delete_appointment'),
    ]

    operations = [
        migrations.AddField(
            model_name='slot',
            name='appointments',
            field=models.ManyToManyField(to='app.Appointment'),
        ),
    ]
