# Generated by Django 3.0.5 on 2020-09-28 21:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0021_slot_appointments"),
    ]

    operations = [
        migrations.AlterField(
            model_name="doctor",
            name="profile",
            field=models.OneToOneField(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="user.Profile",
            ),
        ),
        migrations.AlterField(
            model_name="slot",
            name="date",
            field=models.DateField(null=True, verbose_name="date"),
        ),
        migrations.AlterField(
            model_name="slot",
            name="end_time",
            field=models.TimeField(null=True, verbose_name="end time"),
        ),
        migrations.AlterField(
            model_name="slot",
            name="start_time",
            field=models.TimeField(null=True, verbose_name="start time"),
        ),
    ]
