# Generated by Django 3.0.5 on 2020-09-28 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_auto_20200928_2326'),
        ('user', '0022_auto_20200928_2326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slot',
            name='appointments',
            field=models.ManyToManyField(null=True, to='app.Appointment'),
        ),
    ]
