# Generated by Django 3.0.5 on 2020-10-17 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0026_remove_slot_appointments'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='admin_only',
            field=models.BooleanField(null=True, verbose_name='staff only'),
        ),
    ]
